---
- hosts: all
  become: yes
  tasks:
    - name: Mars client
      ansible.builtin.include_role:
        name: ewc-ansible-role-mars-client

    - name: AIFS ENS CRPS
      ansible.builtin.include_role:
        name: ewc-ansible-role-aifs-ens-crps
