---
# Ansible Requirements
roles:
  - name: ewc-ansible-role-mars-client-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-mars-client.git
    version: 1.0.1

  - name: ewc-ansible-role-conda-1.1
    src: https://github.com/ewcloud/ewc-ansible-role-conda.git
    version: 1.1.0

  - name: ewc-ansible-role-ml-basic-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-ml-basic.git
    version: 1.0.1

  - name: ewc-ansible-role-anemoi-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-anemoi.git
    version: 1.0.1

  - name: ewc-ansible-role-ai-models-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-ai-models.git
    version: 1.0.1

  - name: ewc-ansible-role-aifs-single-mse-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-aifs-single-mse.git
    version: 1.0.1

  - name: ewc-ansible-role-aifs-ens-crps-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-aifs-ens-crps.git
    version: 1.0.1
