---
# Ansible Requirements
roles:
  - name: ewc-ansible-role-mars-client
    src: https://github.com/ewcloud/ewc-ansible-role-mars-client.git
    version: main

  - name: ewc-ansible-role-conda
    src: https://github.com/ewcloud/ewc-ansible-role-conda.git
    version: main

  - name: ewc-ansible-role-ml-basic
    src: https://github.com/ewcloud/ewc-ansible-role-ml-basic.git
    version: main

  - name: ewc-ansible-role-anemoi
    src: https://github.com/ewcloud/ewc-ansible-role-anemoi.git
    version: main

  - name: ewc-ansible-role-ai-models
    src: https://github.com/ewcloud/ewc-ansible-role-ai-models.git
    version: main

  - name: ewc-ansible-role-aifs-single-mse
    src: https://github.com/ewcloud/ewc-ansible-role-aifs-single-mse.git
    version: main

  - name: ewc-ansible-role-aifs-ens-crps
    src: https://github.com/ewcloud/ewc-ansible-role-aifs-ens-crps.git
    version: main
